export const ACTIVITY_LOADING = 'ACTIVITY_LOADING';
export const ACTIVITY_ERROR = 'ACTIVITY_ERROR';
export const ACTIVITY_ENTRIES = 'ACTIVITY_ENTRIES';
export const GET_ACTIVITY = 'GET_ACTIVITY';
export const CLEAR_ACTIVITY = 'CLEAR_ACTIVITY';
