export const GET_MEMBERS = 'GET_MEMBERS';
export const DELETE_MEMBER = 'DELETE_MEMBER';
export const MEMBERS_LOADING = 'MEMBERS_LOADING';
export const MEMBERS_SUCCESS = 'MEMBERS_SUCCESS';
export const MEMBERS_ERROR = 'MEMBERS_ERROR';
