export const GET_ORGANIZATION = 'GET_ORGANIZATION';
export const PUT_ORGANIZATION = 'PUT_ORGANIZATION';
export const ORGANIZATION_LOADING = 'ORGANIZATION_LOADING';
export const ORGANIZATION_SUCCESS = 'ORGANIZATION_SUCCESS';
export const ORGANIZATION_ERROR = 'ORGANIZATION_ERROR';
